name: Lint Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
